---
# tasks file for moodle
 - name: Cria o usuário
   user: name=moobleb

 - name: Cria o diretório do Moodle
   file: dest=/moodle state=directory owner=bguima

 - name: Baixa o Moodle
   get_url: 
    url=https://download.moodle.org/download.php/stable38/moodle-3.8.2.tgz
    dest=/moodle
    validate_certs=no
 - copy:
    src: /moodle/moodle-3.8.2.tgz
    dest: /var/www
 - shell: gzip /tmp/moodle-3.8.2.tgz
# - name: Descompacta o Moodle
#   unarchive: 
    
   
 - name: Modifica permissao pasta Moodle
   file:
    path: /moodle
    owner: bguima

 - name: Atualiza o site Apache padrao
   lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/moodle"

   notify:
    - reinicia apache

 - name: Configura o Cron
   cron: name="Moodle" job="/usr/bin/php moodle/admin/cli/cron.php >/dev/null" 
