---
# tasks file for moodle
 - name: Cria o usuário
   user: name=moobleb

 - name: Cria o diretório do Moodle
   file: dest=/moodle state=directory owner=bguima

 - name: Baixa o Moodle
   get_url: 
    url=https://download.moodle.org/download.php/stable38/moodle-3.8.2.tgz
    dest=/moodle
    validate_certs=no
 - copy:
    src: /moodle/moodle-3.8.2.tgz
    dest: /tmp
 - shell: gzip /tmp/moodle-3.8.2.tgz
# - name: Descompacta o Moodle
#   unarchive: 
    
   
 - name: Modifica permissao pasta wordpress
   file:
    path: /moodle
    owner: bguima
    group: tp3
    mode: "0755"
    recurse: yes
