---
# tasks file for moodle
 - name: Cria o usuário
   user: name="{{ moodle_user }}"

 - name: Cria o diretório do Moodle
   file: dest="{{ moodle_path }}" state=directory owner="{{ moodle_user }}"


 - name: Baixa e instala o Moodle
   git: repo=https://github.com/moodle/moodle.git version="{{ moodle_version }}" dest="{{ moodle_src }}" accept_hostkey=yes

 - name: Configura o Moodle
   template: src=config.php.j2 dest="{{ moodle_src }}/config.php"

 - name: Create o diretório de documentos do Moodle
   file: dest="{{ moodle_docs }}" state=directory owner="{{ moodle_user }}"

 - name: Configura o aqruivo cron
   cron: name="Moodle" job="/usr/bin/php {{ moodle_path }}/admin/cli/cron.php >/dev/null"
